[project]
name = "jax-hydroelastic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beartype>=0.20.2",
    "chex>=0.1.89",
    "jax>=0.5.2",
    "jaxlie>=1.4.2",
    "jaxtyping>=0.3.1",
    "matplotlib>=3.10.1",
    "numpy>=2.2.3",
    "numpy-stl>=3.2.0",
    "pyqt5>=5.15.11",
    "pyvista>=0.44.2",
    "tetgen>=0.6.5",
]
